version: '3.8'

services:
  app:
    build:
      context: ./allright
    command: python manage.py runserver 0.0.0.0:8000
    restart: unless-stopped
    volumes:
      - ./allright/:/home/app/web/
    ports:
      - "8000:8000"
