# Generated by Django 5.0 on 2023-12-26 19:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.post')),
            ],
            bases=('blog.post',),
        ),
        migrations.AddField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de publicação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='midia',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Mídia'),
        ),
    ]
