# Generated by Django 5.0 on 2024-03-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20240128_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroHomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('descricao', models.TextField()),
            ],
        ),
    ]
