# Generated by Django 5.0 on 2024-03-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_cadastrohomepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrohomepage',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='cadastrohomepage',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='cadastrohomepage',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
    ]
