# Generated by Django 5.0 on 2024-03-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_cadastrohomepage_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastrohomepage',
            name='telefone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='cadastrohomepage',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
    ]
